grails-app/domain/ordenacao/InvestigacaoCore.groovy
package ordenacao

class InvestigacaoCore {
    int altura
    int largura
    Ponto crime
    static hasMany = [quadrilhas:Quadrilha]


    String toString() {
        "Crime: (${crime?.x}, ${crime?.y}), Quadrilhas: ${quadrilhas?.size()}"
    }

    static constraints = {
    }
}

grails-app/controllers/ordenacao/InvestigacaoCoreController.groovy
package ordenacao

import grails.converters.JSON
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class InvestigacaoCoreController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def investigacaoCoreService
    static scaffold = true
    def index(Integer max) {
        JSON.use('deep'){
            render InvestigacaoCore.list() as JSON
        }
    }

    def limparBanco() {
        InvestigacaoCore.executeUpdate("delete from InvestigacaoCore p");
        Quadrilha.executeUpdate("delete from Quadrilha p");
        Ponto.executeUpdate("delete from Ponto p");

        JSON.use('deep'){
            render InvestigacaoCore.list() as JSON
        }
    }

    def investigarCrime() {
        InvestigacaoCore inves;

        def list = InvestigacaoCore.withCriteria{
            sqlRestriction " 1=1 order by rand()"
        }
        if (list) {
            inves = list.get(0)
        }
        JSON.use('deep'){
            render investigacaoCoreService.analisarCrime(inves) as JSON
        }

    }

    def autoIt(){
        investigacaoCoreService.novaInvestigacao()
    }

    def create() {
        respond new InvestigacaoCore(params)
    }

    @Transactional
    def save() {
        Ponto crime = Ponto.findById(params.crime)
        InvestigacaoCore investigacaoCoreInstance = new InvestigacaoCore(crime:crime, largura:800, altura:600)
        params.get("quads[]").each {
            investigacaoCoreInstance.addToQuadrilhas(Quadrilha.findById(it))
        }
        if (investigacaoCoreInstance == null) {
            notFound()
            return
        }

        if (investigacaoCoreInstance.hasErrors()) {
            respond investigacaoCoreInstance.errors, view:'create'
            return
        }

        investigacaoCoreInstance.save(flush:true)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'investigacaoCore.label', default: 'InvestigacaoCore'), investigacaoCoreInstance.id])
                redirect investigacaoCoreInstance
            }
            '*' { respond investigacaoCoreInstance, [status: CREATED] }
        }
    }
}

grails-app/views/investigacaoCore/_form.gsp
<%@ page import="ordenacao.InvestigacaoCore" %>



<div class="fieldcontain ${hasErrors(bean: investigacaoCoreInstance, field: 'altura', 'error')} required">
	<label for="altura">
		<g:message code="investigacaoCore.altura.label" default="Altura" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="altura" type="number" value="${investigacaoCoreInstance.altura}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: investigacaoCoreInstance, field: 'crime', 'error')} required">
	<label for="crime">
		<g:message code="investigacaoCore.crime.label" default="Crime" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="crime" name="crime.id" from="${ordenacao.Ponto.list()}" optionKey="id" required="" value="${investigacaoCoreInstance?.crime?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: investigacaoCoreInstance, field: 'largura', 'error')} required">
	<label for="largura">
		<g:message code="investigacaoCore.largura.label" default="Largura" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="largura" type="number" value="${investigacaoCoreInstance.largura}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: investigacaoCoreInstance, field: 'quadrilhas', 'error')} ">
	<label for="quadrilhas">
		<g:message code="investigacaoCore.quadrilhas.label" default="Quadrilhas" />
		
	</label>
	<g:select name="quadrilhas" from="${ordenacao.Quadrilha.list()}" multiple="multiple" optionKey="id" size="5" value="${investigacaoCoreInstance?.quadrilhas*.id}" class="many-to-many"/>

</div>

grails-app/views/investigacaoCore/create.gsp
		<div id="create-investigacaoCore" class="content scaffold-create" role="main">
			<h1>Criar Investigação</h1>
				<fieldset class="form">

					<div class="fieldcontain ${hasErrors(bean: investigacaoCoreInstance, field: 'crime', 'error')} required">
						<label for="crime">
							<g:message code="investigacaoCore.crime.label" default="Crime" />
							<span class="required-indicator">*</span>
						</label>
						<g:select id="crime-crime" name="crime.id" from="${ordenacao.Ponto.newList()}" optionKey="id" optionValue="name" required="" value="" class="many-to-one"/>

					</div>


					<div class="fieldcontain ${hasErrors(bean: investigacaoCoreInstance, field: 'quadrilhas', 'error')} ">
						<label for="quadrilhas">
							<g:message code="investigacaoCore.quadrilhas.label" default="Quadrilhas" />

						</label>
						<g:select id="crime-quad" name="quadrilhas" from="${ordenacao.Quadrilha.newList()}" multiple="multiple" optionKey="id" optionValue="nome" size="5" value="" class="many-to-many"/>

					</div>
				</fieldset>
				<fieldset class="buttons">
					<input type="button" name="createCrime" value="Criar Investigação" class="save" onclick="saveCrime()">
				</fieldset>
			</div>

grails-app/views/investigacaoCore/edit.gsp
<%@ page import="ordenacao.InvestigacaoCore" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'investigacaoCore.label', default: 'InvestigacaoCore')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-investigacaoCore" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-investigacaoCore" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${investigacaoCoreInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${investigacaoCoreInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:investigacaoCoreInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${investigacaoCoreInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/investigacaoCore/index.gsp
<%@ page import="ordenacao.InvestigacaoCore" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'investigacaoCore.label', default: 'InvestigacaoCore')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-investigacaoCore" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-investigacaoCore" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="altura" title="${message(code: 'investigacaoCore.altura.label', default: 'Altura')}" />
					
						<th><g:message code="investigacaoCore.crime.label" default="Crime" /></th>
					
						<g:sortableColumn property="largura" title="${message(code: 'investigacaoCore.largura.label', default: 'Largura')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${investigacaoCoreInstanceList}" status="i" var="investigacaoCoreInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${investigacaoCoreInstance.id}">${fieldValue(bean: investigacaoCoreInstance, field: "altura")}</g:link></td>
					
						<td>${fieldValue(bean: investigacaoCoreInstance, field: "crime")}</td>
					
						<td>${fieldValue(bean: investigacaoCoreInstance, field: "largura")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${investigacaoCoreInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/investigacaoCore/show.gsp
<%@ page import="ordenacao.InvestigacaoCore" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'investigacaoCore.label', default: 'InvestigacaoCore')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-investigacaoCore" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-investigacaoCore" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list investigacaoCore">
			
				<g:if test="${investigacaoCoreInstance?.altura}">
				<li class="fieldcontain">
					<span id="altura-label" class="property-label"><g:message code="investigacaoCore.altura.label" default="Altura" /></span>
					
						<span class="property-value" aria-labelledby="altura-label"><g:fieldValue bean="${investigacaoCoreInstance}" field="altura"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${investigacaoCoreInstance?.crime}">
				<li class="fieldcontain">
					<span id="crime-label" class="property-label"><g:message code="investigacaoCore.crime.label" default="Crime" /></span>
					
						<span class="property-value" aria-labelledby="crime-label"><g:link controller="ponto" action="show" id="${investigacaoCoreInstance?.crime?.id}">${investigacaoCoreInstance?.crime?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${investigacaoCoreInstance?.largura}">
				<li class="fieldcontain">
					<span id="largura-label" class="property-label"><g:message code="investigacaoCore.largura.label" default="Largura" /></span>
					
						<span class="property-value" aria-labelledby="largura-label"><g:fieldValue bean="${investigacaoCoreInstance}" field="largura"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${investigacaoCoreInstance?.quadrilhas}">
				<li class="fieldcontain">
					<span id="quadrilhas-label" class="property-label"><g:message code="investigacaoCore.quadrilhas.label" default="Quadrilhas" /></span>
					
						<g:each in="${investigacaoCoreInstance.quadrilhas}" var="q">
						<span class="property-value" aria-labelledby="quadrilhas-label"><g:link controller="quadrilha" action="show" id="${q.id}">${q?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:investigacaoCoreInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${investigacaoCoreInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>