grails-app/domain/ordenacao/Quadrilha.groovy
package ordenacao

class Quadrilha {
    String nome
    static hasMany = [ pontos:Ponto]

    String toString(){
        "$nome (${pontos?.size()} pontos)"
    }

    static constraints = {
    }

    static ArrayList<Quadrilha> newList(){
        ArrayList<Quadrilha> quads = new ArrayList<Quadrilha>();
        ArrayList<InvestigacaoCore> inves = InvestigacaoCore.list()
        inves.each {
            quads.addAll(it.quadrilhas)
        }

        (Quadrilha.list()-quads)
    }

}

grails-app/controllers/ordenacao/QuadrilhaController.groovy
package ordenacao

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import grails.converters.JSON

@Transactional(readOnly = true)
class QuadrilhaController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    static scaffold = true

    def index() {
        JSON.use('deep'){
            render Quadrilha.list() as JSON
        }
    }

    def listByInvestigacao(){
        ArrayList<Quadrilha> quads = new ArrayList<Quadrilha>();
        ArrayList<InvestigacaoCore> inves = InvestigacaoCore.list()
        inves.each {
            quads.addAll(it.quadrilhas)
        }

        return (Quadrilha.list()-quads)
    }

    def show(Quadrilha quadrilhaInstance) {
        respond quadrilhaInstance
    }

    def create() {
        respond new Quadrilha(params), model:[quadrilhaList:listByInvestigacao()]
    }

    @Transactional
    def save(String nome) {
        Quadrilha quadrilhaInstance = new Quadrilha(nome:nome)
        def pontos = params.get("pontos[]")
        pontos.each {
            quadrilhaInstance.addToPontos(Ponto.findById(it))
        }

        if (quadrilhaInstance == null) {
            notFound()
            return
        }

        if (quadrilhaInstance.hasErrors()) {
            respond quadrilhaInstance.errors, view:'create'
            return
        }

        quadrilhaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'quadrilha.label', default: 'Quadrilha'), quadrilhaInstance.id])
                redirect quadrilhaInstance
            }
            '*' { respond quadrilhaInstance, [status: CREATED] }
        }
    }

    def edit(Quadrilha quadrilhaInstance) {
        respond quadrilhaInstance
    }

    @Transactional
    def update(Quadrilha quadrilhaInstance) {
        if (quadrilhaInstance == null) {
            notFound()
            return
        }

        if (quadrilhaInstance.hasErrors()) {
            respond quadrilhaInstance.errors, view:'edit'
            return
        }

        quadrilhaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Quadrilha.label', default: 'Quadrilha'), quadrilhaInstance.id])
                redirect quadrilhaInstance
            }
            '*'{ respond quadrilhaInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Quadrilha quadrilhaInstance) {

        if (quadrilhaInstance == null) {
            notFound()
            return
        }

        quadrilhaInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Quadrilha.label', default: 'Quadrilha'), quadrilhaInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'quadrilha.label', default: 'Quadrilha'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/quadrilha/_form.gsp
<%@ page import="ordenacao.Quadrilha" %>



<div class="fieldcontain ${hasErrors(bean: quadrilhaInstance, field: 'nome', 'error')} required">
	<label for="nome">
		<g:message code="quadrilha.nome.label" default="Nome" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nome" required="" value="${quadrilhaInstance?.nome}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: quadrilhaInstance, field: 'pontos', 'error')} ">
	<label for="pontos">
		<g:message code="quadrilha.pontos.label" default="Pontos" />
		
	</label>
	<g:select name="pontos" from="${ordenacao.Ponto.list()}" multiple="multiple" optionKey="id" size="5" value="${quadrilhaInstance?.pontos*.id}" class="many-to-many"/>

</div>

grails-app/views/quadrilha/create.gsp
<%@ page import="ordenacao.*" %>
<%@ page import grails.converters.JSON %>
		<div id="create-quadrilha" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="['Quadrilha']" /></h1>
			<g:form url="[resource:quadrilhaInstance, action:'save']" >
				<fieldset class="form">
					<div class="fieldcontain ${hasErrors(bean: quadrilhaInstance, field: 'nome', 'error')} required">
						<label for="nome">
							<g:message code="quadrilha.nome.label" default="Nome" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField id="quad-nome" name="nome" required="" value=""/>

					</div>

					<div class="fieldcontain ${hasErrors(bean: quadrilhaInstance, field: 'pontos', 'error')} ">
						<label for="pontos">
							<g:message code="quadrilha.pontos.label" default="Pontos" />

						</label>

						<g:select id="quad-pontos" name="pontos" from="${ordenacao.Ponto.newList()}" multiple="multiple" optionKey="id" optionValue="name" size="5" value="${quadrilhaInstance?.pontos*.id}" class="many-to-many"/>
					</div>
				</fieldset>
				<fieldset class="buttons">
					<input type="button" name="createQuad" value="Criar Quadrilha" class="save" onclick="saveQuad()">
				</fieldset>
			</g:form>
		</div>

grails-app/views/quadrilha/edit.gsp
<%@ page import="ordenacao.Quadrilha" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'quadrilha.label', default: 'Quadrilha')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-quadrilha" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-quadrilha" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${quadrilhaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${quadrilhaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:quadrilhaInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${quadrilhaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/quadrilha/index.gsp
<%@ page import="ordenacao.Quadrilha" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'quadrilha.label', default: 'Quadrilha')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-quadrilha" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-quadrilha" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nome" title="${message(code: 'quadrilha.nome.label', default: 'Nome')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${quadrilhaInstanceList}" status="i" var="quadrilhaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${quadrilhaInstance.id}">${fieldValue(bean: quadrilhaInstance, field: "nome")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${quadrilhaInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/quadrilha/show.gsp
<%@ page import="ordenacao.Quadrilha" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'quadrilha.label', default: 'Quadrilha')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-quadrilha" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-quadrilha" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list quadrilha">
			
				<g:if test="${quadrilhaInstance?.nome}">
				<li class="fieldcontain">
					<span id="nome-label" class="property-label"><g:message code="quadrilha.nome.label" default="Nome" /></span>
					
						<span class="property-value" aria-labelledby="nome-label"><g:fieldValue bean="${quadrilhaInstance}" field="nome"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${quadrilhaInstance?.pontos}">
				<li class="fieldcontain">
					<span id="pontos-label" class="property-label"><g:message code="quadrilha.pontos.label" default="Pontos" /></span>
					
						<g:each in="${quadrilhaInstance.pontos}" var="p">
						<span class="property-value" aria-labelledby="pontos-label"><g:link controller="ponto" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:quadrilhaInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${quadrilhaInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>